# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - id: 2
    uid: loki
    orgId: 1
    name: Loki
    type: loki
    typeName: Loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: \"traceid\":\"(\w+)\"
          name: TraceID
          url: "${__value.raw}"
          urlDisplayLabel: View Trace
      maxLines: 1000
    readOnly: false
  - id: 1
    uid: mimir
    orgId: 1
    name: Mimir
    type: prometheus
    typeName: Prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    basicAuth: false
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
        - name: trace_id
          url: http://tempo:3200/trace/${__value.raw}
          urlDisplayLabel: View in Jaeger UI
    readOnly: false
  - id: 3
    uid: tempo
    orgId: 1
    name: Tempo
    type: tempo
    typeName: Tempo
    typeLogoUrl: "/grafana/public/app/plugins/datasource/tempo/img/tempo_logo.svg"
    access: proxy
    url: http://tempo:3200
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      httpMethod: GET
      lokiSearch:
        datasourceUid: loki
      nodeGraph:
        enabled: true
      search:
        filters:
          - id: service-name
            operator: "="
            scope: resource
            tag: service.name
          - id: span-name
            operator: "="
            scope: span
            tag: name
        hide: true
      serviceMap:
        datasourceUid: mimir
      traceQuery:
        timeShiftEnabled: true
      tracesToLogsV2:
        customQuery: false
        datasourceUid: loki
        filterByTraceID: true
        query: job=~".*${__tags.service.name}" |= "${__trace.traceId}"
        tags: []
    readOnly: false
